### ISSUE TITLE
All examles show ReferenceError: L20n is not defined

### ISSUE THREAD

**Issue by spagy** [l20n/tinker#2]
Currently all examples show 
```
ReferenceError
    L20n is not defined
```
in the place where I would expect to see the translations.

**Comment by stasm** [comment]
My bad, last week I updated l20n.js that runs in tinker and I used the non-transpiled version.  It uses the `for (const ... of ...)` syntax which only works in Firefox 51+ (stable release due in January).

**Comment by stasm** [comment]
Fixed in 78c1963deeb316d81fb7d590a075dcf135e0eda3. Thanks for the report!
